# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: F:/MyTemporary/Github/PhotonDetector/Processing_Board/Firmware/ZPhotonDetector/ZVerilog/ZConstraint_IO.xdc

# Block Designs: F:/MyTemporary/Github/PhotonDetector/Processing_Board/Firmware/ZPhotonDetector/ZVerilog/ZBlocks/ZPhotonDetector_Block/ZPhotonDetector_Block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZPhotonDetector_Block || ORIG_REF_NAME==ZPhotonDetector_Block} -quiet] -quiet

# IP: F:/MyTemporary/Github/PhotonDetector/Processing_Board/Firmware/ZPhotonDetector/ZVerilog/ZBlocks/ZPhotonDetector_Block/ip/ZPhotonDetector_Block_clk_wiz_0_0/ZPhotonDetector_Block_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZPhotonDetector_Block_clk_wiz_0_0 || ORIG_REF_NAME==ZPhotonDetector_Block_clk_wiz_0_0} -quiet] -quiet

# IP: F:/MyTemporary/Github/PhotonDetector/Processing_Board/Firmware/ZPhotonDetector/ZVerilog/ZBlocks/ZPhotonDetector_Block/ip/ZPhotonDetector_Block_ZPower_EN_0_0/ZPhotonDetector_Block_ZPower_EN_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZPhotonDetector_Block_ZPower_EN_0_0 || ORIG_REF_NAME==ZPhotonDetector_Block_ZPower_EN_0_0} -quiet] -quiet

# IP: F:/MyTemporary/Github/PhotonDetector/Processing_Board/Firmware/ZPhotonDetector/ZVerilog/ZBlocks/ZPhotonDetector_Block/ip/ZPhotonDetector_Block_ZEdge_Detect_0_0/ZPhotonDetector_Block_ZEdge_Detect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZPhotonDetector_Block_ZEdge_Detect_0_0 || ORIG_REF_NAME==ZPhotonDetector_Block_ZEdge_Detect_0_0} -quiet] -quiet

# IP: F:/MyTemporary/Github/PhotonDetector/Processing_Board/Firmware/ZPhotonDetector/ZVerilog/ZBlocks/ZPhotonDetector_Block/ip/ZPhotonDetector_Block_ZLed_Indicator_0_0/ZPhotonDetector_Block_ZLed_Indicator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZPhotonDetector_Block_ZLed_Indicator_0_0 || ORIG_REF_NAME==ZPhotonDetector_Block_ZLed_Indicator_0_0} -quiet] -quiet

# IP: F:/MyTemporary/Github/PhotonDetector/Processing_Board/Firmware/ZPhotonDetector/ZVerilog/ZBlocks/ZPhotonDetector_Block/ip/ZPhotonDetector_Block_ZMux2to1_0_0/ZPhotonDetector_Block_ZMux2to1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZPhotonDetector_Block_ZMux2to1_0_0 || ORIG_REF_NAME==ZPhotonDetector_Block_ZMux2to1_0_0} -quiet] -quiet

# IP: F:/MyTemporary/Github/PhotonDetector/Processing_Board/Firmware/ZPhotonDetector/ZVerilog/ZBlocks/ZPhotonDetector_Block/ip/ZPhotonDetector_Block_ZUART_Data_Dump_0_0/ZPhotonDetector_Block_ZUART_Data_Dump_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZPhotonDetector_Block_ZUART_Data_Dump_0_0 || ORIG_REF_NAME==ZPhotonDetector_Block_ZUART_Data_Dump_0_0} -quiet] -quiet

# IP: F:/MyTemporary/Github/PhotonDetector/Processing_Board/Firmware/ZPhotonDetector/ZVerilog/ZBlocks/ZPhotonDetector_Block/ip/ZPhotonDetector_Block_ZPulse_Counter_0_0/ZPhotonDetector_Block_ZPulse_Counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZPhotonDetector_Block_ZPulse_Counter_0_0 || ORIG_REF_NAME==ZPhotonDetector_Block_ZPulse_Counter_0_0} -quiet] -quiet

# IP: F:/MyTemporary/Github/PhotonDetector/Processing_Board/Firmware/ZPhotonDetector/ZVerilog/ZBlocks/ZPhotonDetector_Block/ip/ZPhotonDetector_Block_ZExtSig_Simulator_0_0/ZPhotonDetector_Block_ZExtSig_Simulator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZPhotonDetector_Block_ZExtSig_Simulator_0_0 || ORIG_REF_NAME==ZPhotonDetector_Block_ZExtSig_Simulator_0_0} -quiet] -quiet

# IP: F:/MyTemporary/Github/PhotonDetector/Processing_Board/Firmware/ZPhotonDetector/ZVerilog/ZBlocks/ZPhotonDetector_Block/ip/ZPhotonDetector_Block_ZTest_Generator_0_0/ZPhotonDetector_Block_ZTest_Generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZPhotonDetector_Block_ZTest_Generator_0_0 || ORIG_REF_NAME==ZPhotonDetector_Block_ZTest_Generator_0_0} -quiet] -quiet

# XDC: F:/MyTemporary/Github/PhotonDetector/Processing_Board/Firmware/ZPhotonDetector/ZVerilog/ZBlocks/ZPhotonDetector_Block/ZPhotonDetector_Block_ooc.xdc
