set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ZPhotonDetector_Block_i/clk_wiz_0/inst/clk_in1_ZPhotonDetector_Block_clk_wiz_0_0]

set_property PACKAGE_PIN H11 [get_ports {oLED[0]}]
set_property PACKAGE_PIN D3 [get_ports {oLED[1]}]
set_property PACKAGE_PIN P3 [get_ports iPulse]
set_property PACKAGE_PIN B5 [get_ports oRS485_Dir2]
set_property PACKAGE_PIN H3 [get_ports iClk]
set_property PACKAGE_PIN J1 [get_ports oIO_J1]
set_property IOSTANDARD LVCMOS33 [get_ports {oLED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oLED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports iClk]
set_property IOSTANDARD LVCMOS33 [get_ports iPulse]
set_property IOSTANDARD LVCMOS33 [get_ports oIO_J1]
set_property IOSTANDARD LVCMOS33 [get_ports oRS485_Dir2]
set_property IOSTANDARD LVCMOS33 [get_ports oRS485_Txd2]
set_property IOSTANDARD LVCMOS33 [get_ports oRS485_Dir1]
set_property IOSTANDARD LVCMOS33 [get_ports oRS485_Txd1]

set_property PULLUP true [get_ports oIO_J1]

set_property PACKAGE_PIN L1 [get_ports oRS485_Txd1]
set_property PACKAGE_PIN C5 [get_ports oRS485_Txd2]
set_property PACKAGE_PIN L2 [get_ports oRS485_Dir1]


set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[11]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[15]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[17]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[19]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[20]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[22]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[23]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[12]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[16]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[18]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[21]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[25]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[13]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[14]}]



set_property MARK_DEBUG false [get_nets ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewDataUpdate]
set_property MARK_DEBUG false [get_nets ZPhotonDetector_Block_i/ZPulse_Counter_0/iPulse]
set_property MARK_DEBUG false [get_nets ZPhotonDetector_Block_i/ZPulse_Counter_0/iClk]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[0]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[1]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[2]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[3]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[6]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[10]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[5]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[7]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[8]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[11]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[12]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[4]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[13]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[14]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[9]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[15]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT_Deadline[12]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT_Deadline[13]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT_Deadline[14]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT_Deadline[16]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT_Deadline[11]}]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT_Deadline[15]}]
set_property MARK_DEBUG true [get_nets ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewDataUpdate]
set_property MARK_DEBUG true [get_nets ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/iPulse]
set_property MARK_DEBUG true [get_nets ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[1]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[2]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[3]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[8]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[11]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[0]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[6]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[10]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[13]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[4]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[7]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[9]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[14]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[15]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[5]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[12]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[0]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[1]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[2]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[3]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[4]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[5]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[6]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[7]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[8]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[9]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[10]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[11]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[12]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[13]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[14]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[15]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[16]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[17]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[18]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[19]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[20]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[21]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[22]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[23]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[24]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[25]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[26]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[27]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[28]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[29]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[30]}]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[31]}]

connect_debug_port u_ila_0/clk [get_nets [list u_ila_0_clk_50M]]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_50M]


set_property MARK_DEBUG false [get_nets ZPhotonDetector_Block_i/clk_wiz_0/inst/clk_100M_ZPhotonDetector_Block_clk_wiz_0_0]
set_property MARK_DEBUG false [get_nets ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/iClk]
set_property MARK_DEBUG false [get_nets ZPhotonDetector_Block_i/clk_wiz_0/inst/clk_50M]

set_property MARK_DEBUG false [get_nets ZPhotonDetector_Block_i/clk_wiz_0/inst/clk_100M]
set_property MARK_DEBUG false [get_nets ZPhotonDetector_Block_i/clk_wiz_0/inst/clk_50M_ZPhotonDetector_Block_clk_wiz_0_0]
connect_debug_port dbg_hub/clk [get_nets u_ila_1_clkfbout_buf_ZPhotonDetector_Block_clk_wiz_0_0]

