set_property SRC_FILE_INFO {cfile:F:/MyTemporary/Github/PhotonDetector/Processing_Board/Firmware/ZPhotonDetector/ZVerilog/ZConstraint_IO.xdc rfile:../../../ZVerilog/ZConstraint_IO.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ZPhotonDetector_Block_i/clk_wiz_0/inst/clk_in1_ZPhotonDetector_Block_clk_wiz_0_0]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H11 [get_ports {oLED[0]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D3 [get_ports {oLED[1]}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P3 [get_ports iPulse]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B5 [get_ports oRS485_Dir2]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H3 [get_ports iClk]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J1 [get_ports oIO_J1]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1 [get_ports oRS485_Txd1]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C5 [get_ports oRS485_Txd2]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L2 [get_ports oRS485_Dir1]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[11]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[15]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[17]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[19]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[20]}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[22]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[23]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[12]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[16]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[18]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[21]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[25]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[13]}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal0[14]}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewDataUpdate]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets ZPhotonDetector_Block_i/ZPulse_Counter_0/iPulse]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets ZPhotonDetector_Block_i/ZPulse_Counter_0/iClk]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[0]}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[1]}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[2]}]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[3]}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[6]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[10]}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[5]}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[7]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[8]}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[11]}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[12]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[4]}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[13]}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[14]}]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[9]}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/oNewPulseCounter[15]}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT_Deadline[12]}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT_Deadline[13]}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT_Deadline[14]}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT_Deadline[16]}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT_Deadline[11]}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT_Deadline[15]}]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewDataUpdate]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/iPulse]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[1]}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[2]}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[3]}]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[8]}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[11]}]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[0]}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[6]}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[10]}]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[13]}]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[4]}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[7]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[9]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[14]}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[15]}]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[5]}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[12]}]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[0]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[1]}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[2]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[3]}]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[4]}]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[5]}]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[6]}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[7]}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[8]}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[9]}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[10]}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[11]}]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[12]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[13]}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[14]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[15]}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[16]}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[17]}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[18]}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[19]}]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[20]}]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[21]}]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[22]}]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[23]}]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[24]}]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[25]}]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[26]}]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[27]}]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[28]}]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[29]}]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[30]}]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[31]}]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list u_ila_0_clk_50M]]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_50M]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets ZPhotonDetector_Block_i/clk_wiz_0/inst/clk_100M_ZPhotonDetector_Block_clk_wiz_0_0]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/iClk]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets ZPhotonDetector_Block_i/clk_wiz_0/inst/clk_50M]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets ZPhotonDetector_Block_i/clk_wiz_0/inst/clk_100M]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets ZPhotonDetector_Block_i/clk_wiz_0/inst/clk_50M_ZPhotonDetector_Block_clk_wiz_0_0]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 65536 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list ZPhotonDetector_Block_i/clk_wiz_0/inst/clk_50M]]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[0]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[1]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[2]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[3]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[4]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[5]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[6]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[7]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[8]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[9]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[10]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[11]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[12]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[13]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[14]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[15]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[16]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[17]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[18]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[19]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[20]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[21]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[22]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[23]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[24]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[25]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[26]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[27]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[28]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[29]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[30]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/CNT[31]}]]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[0]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[1]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[2]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[3]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[4]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[5]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[6]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[7]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[8]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[9]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[10]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[11]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[12]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[13]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[14]} {ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewPulseCounter[15]}]]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/iPulse]]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/oNewDataUpdate]]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list ZPhotonDetector_Block_i/ZPulse_Counter_0/inst/zero_signal]]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_1_clkfbout_buf_ZPhotonDetector_Block_clk_wiz_0_0]
